### ISSUE TITLE
invalid command name "molUP::start"

### ISSUE THREAD

**Issue by maojinyuan** [portobiocomp/molUP#2]
I do the instruction, and I just see the "molUP" in "Extensions">"VMD Store">"molUP", however I get this problem, and I didn't find the thing what I need to be modifed, could you help me ?

below are the error messages:
> The molUP package could not be loaded:

> vmd > ERROR) Creation of window for 'molUP' failed (invalid command name "molUP::start").

**Comment by henriquefer** [comment]
Hi,

In order to help you, please let me know some additional info:

- Operating System
- VMD version
- Installation method used
- Content of the .vmdrc or vmd.rc file

Best regards

**Comment by maojinyuan** [comment]
Hi,
1. Linux(centos6)
2. vmd1.9.4
3. cause my VMDstore is loading, can't going to install molUP，so I install it by myself.
4. the code in vmdrc
> ##### VMD Store ## START #####
> play "/share/home/maojy/vmd1.9.4a35/vmdStore/vmdStore.rc"
> ##### VMD Store ## END #####
> menu main on
> 
> ####vmdStore#### START molUP
> #### Version XXversionXX
> ##variable molUPpath "$::/share/home/maojy/vmd1.9.4a35/molUP"
> ##lappend auto_path $::molUPpath
> ##vmd_install_extension molUP "molUP::start" "VMD Store/molUP" 
> ######vmdStore#### END molUP

**Comment by henriquefer** [comment]
Please, replace the following lines:

```
Version XXversionXX

##variable molUPpath "$::/share/home/maojy/vmd1.9.4a35/molUP"
##lappend auto_path $::molUPpath
##vmd_install_extension molUP "molUP::start" "VMD Store/molUP"
######vmdStore#### END molUP
```

by:

```
####vmdStore#### START molUP
## Version 1.5.4
variable molUPpath "/share/home/maojy/vmd1.9.4a35/molUP"
lappend auto_path $::molUPpath
vmd_install_extension molUP "molUP::start" "VMD Store/molUP" 
####vmdStore#### END molUP
```

Basically, you have to remove "$::" from the variable molUPpath line and remove "##" from all the lines that are not comments. 

----

3. Let me know the issues that are you getting with the VMD Store. If you want, I would appreciate that you open an issue here: https://github.com/BioSIM-Research-Group/vmdStore

Thank you.
Best regards

**Comment by henriquefer** [comment]
https://github.com/BioSIM-Research-Group/vmdStore/issues/1

@maojinyuan :

> BTW, I do the examples as the introduction of molUP, and I get the Gaussian input file and execute it, however, it was repored "MM function not complete" as below, I found the undefined bondstretch and angle bend were exactly the positions of cutten amino acid residues, I wonder this parameters can be added manually or can be added automatically in your package(molUP)?
cause I didn't find some related tutorial to avoid this problem.

```
Include all MM classes
Bondstretch undefined between atoms 1209 1211 C-H [H,L]
Bondstretch undefined between atoms 2174 2176 C-H [H,L]
Bondstretch undefined between atoms 3074 3076 C-H [H,L]
Bondstretch undefined between atoms 3864 3866 C-H [H,L]
Angle bend undefined between atoms 1202 1209 1211 CT-C-H [H,H,L]
Angle bend undefined between atoms 1210 1209 1211 O-C-H [H,H,L]
Angle bend undefined between atoms 2167 2174 2176 CT-C-H [H,H,L]
Angle bend undefined between atoms 2175 2174 2176 O-C-H [H,H,L]
Angle bend undefined between atoms 3066 3074 3076 CT-C-H [H,H,L]
Angle bend undefined between atoms 3075 3074 3076 O-C-H [H,H,L]
Angle bend undefined between atoms 3851 3864 3866 CT-C-H [H,H,L]
Angle bend undefined between atoms 3865 3864 3866 O-C-H [H,H,L]
MM function not complete
Error termination via Lnk1e in /share/apps/g16.b01/g16/l120.exe at Wed Sep 4 19:21:11 2019.

```

@henriquefer:

molUP does not automatically provide additional parameters.
When the layers are split between atoms with hydrogens bonded, you have no problem because Gaussian will use the available parameters. 
For example, consider the following molecule. 
```
  H H
  | |
H-C-C-H
  | |
  H H
```
If you split the system in two-layer through the C-C bond, Gaussian will not comply about missing parameters because the link-atom is an H and the parameters for that type of bond and angles already exist.

However, if your molecule is something like:
```
  H F
  | |
H-C-C-Cl
  | |
  H Br
```

Considering the same two-layer system, the second C does not have parameters for the C-H bond required by the link-atom addition. In this case, you have to provide suitable parameters for the link-atoms.

I hope that this helps you understand the procedure.

In your particular case, you have to identify the atom type of heavy those (e.g. 1209) and add a line on your parameters section:
```
HrmStr1 CT H 340.00 1.0900
```
where 340.0 is the force constant and 1.0900 is the equilibrium value.

This also applies to angles bends:
```
HrmBnd1  C  N  H  50.00 120.0001
```
